### ISSUE TITLE
Logout event not managed

### ISSUE THREAD

**Issue by naudinthomas** [trax-project/moodle-trax-logs#4]
Moodle version : 3.6.2+ (Build: 2019012400)
Plugin Trax version : v0.14 (Build: 2018050814)

LRS : Learning Locker v2.5.5

Hello,

We have noticed that, although planned in the code of the logstore_trax plugin, the user logout event is not sent to our LRS.

**Comment by sfraysse** [comment]
You are right if you are in synchronous mode (test). The reason is that the loggout action is performed before the plugin have time to catch the loggout event and send the request to the LRS.

It should work in asynchronous mode (production) because a log is immediatly written is the standard Moodle logstore during the loggout action, and then will be processed by the plugin during a CRON task.
